name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Codecov Coverage Action
        uses: codecov/codecov-action@v1.0.13

    # Quarantine
    # - name: Code Climate Coverage Action
    #   uses: paambaati/codeclimate-action@v2.7.4
    #   env:
    #       CC_TEST_REPORTER_ID: 97488220da208c44cbce579e30d33cdac571190d840163267a5e9c57d42d7c90
    #   with:
    #     coverageCommand: npm test
